// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTD7-JvigUScMs7UUj9LdBnLSXmMtrKfs',
    appId: '1:207289243749:web:6359690bfe7d22dff20e8c',
    messagingSenderId: '207289243749',
    projectId: 'school-parent-app-c46ee',
    authDomain: 'school-parent-app-c46ee.firebaseapp.com',
    storageBucket: 'school-parent-app-c46ee.firebasestorage.app',
    measurementId: 'G-JV8PCQ3D5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM0xuJldMjXR-lziXpPdmdyx3sbvS4KQM',
    appId: '1:207289243749:android:72cacb6bd7d6d986f20e8c',
    messagingSenderId: '207289243749',
    projectId: 'school-parent-app-c46ee',
    storageBucket: 'school-parent-app-c46ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATKVc2tjetVP3570E8ma0Rw82qykPCTSs',
    appId: '1:207289243749:ios:e5fd383aab01a75cf20e8c',
    messagingSenderId: '207289243749',
    projectId: 'school-parent-app-c46ee',
    storageBucket: 'school-parent-app-c46ee.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATKVc2tjetVP3570E8ma0Rw82qykPCTSs',
    appId: '1:207289243749:ios:e5fd383aab01a75cf20e8c',
    messagingSenderId: '207289243749',
    projectId: 'school-parent-app-c46ee',
    storageBucket: 'school-parent-app-c46ee.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTD7-JvigUScMs7UUj9LdBnLSXmMtrKfs',
    appId: '1:207289243749:web:45c010e89f29d41bf20e8c',
    messagingSenderId: '207289243749',
    projectId: 'school-parent-app-c46ee',
    authDomain: 'school-parent-app-c46ee.firebaseapp.com',
    storageBucket: 'school-parent-app-c46ee.firebasestorage.app',
    measurementId: 'G-GWN2Z59DWS',
  );
}// TODO Implement this library.