// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqLRZK_JWq6gPm-fMg9sOdAOZku7p-Zk',
    appId: '1:345125267310:web:29b6c078f614b78f40c37f',
    messagingSenderId: '345125267310',
    projectId: 'study-planner-4bb9c',
    authDomain: 'study-planner-4bb9c.firebaseapp.com',
    storageBucket: 'study-planner-4bb9c.firebasestorage.app',
    measurementId: 'G-VNT60Q2PDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzlERLcMF6JKaSgwh6WC19Ix4H9XFnTms',
    appId: '1:345125267310:android:e78c85dd0fd2c77240c37f',
    messagingSenderId: '345125267310',
    projectId: 'study-planner-4bb9c',
    storageBucket: 'study-planner-4bb9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkMwpVSrEiKfy1oQiB6TqBxmfvlvKQ1aY',
    appId: '1:345125267310:ios:34d710569fd009d040c37f',
    messagingSenderId: '345125267310',
    projectId: 'study-planner-4bb9c',
    storageBucket: 'study-planner-4bb9c.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkMwpVSrEiKfy1oQiB6TqBxmfvlvKQ1aY',
    appId: '1:345125267310:ios:34d710569fd009d040c37f',
    messagingSenderId: '345125267310',
    projectId: 'study-planner-4bb9c',
    storageBucket: 'study-planner-4bb9c.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLqLRZK_JWq6gPm-fMg9sOdAOZku7p-Zk',
    appId: '1:345125267310:web:63d27cb7f5c4c00d40c37f',
    messagingSenderId: '345125267310',
    projectId: 'study-planner-4bb9c',
    authDomain: 'study-planner-4bb9c.firebaseapp.com',
    storageBucket: 'study-planner-4bb9c.firebasestorage.app',
    measurementId: 'G-H9NYXWZPVF',
  );
}